services:
  backend:
    build: ./backend
    # Порт 8000 наружу можно даже не прокидывать, Nginx достучится до него внутри сети
    volumes:
      - ./backend/data:/app/data
    environment:
      - UPLOAD_DIR=data

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
